# Generated by Django 4.1.3 on 2022-11-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dorms',
            new_name='Dorm',
        ),
    ]
