# Generated by Django 4.1.3 on 2022-11-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dorm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
