# Generated by Django 4.1.3 on 2022-11-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_dorm_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorm',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/images'),
        ),
    ]
